<?php

use Illuminate\Database\Seeder;

class SystemWindowSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    protected function databaseConnection()
    {
        return DB::connection('mysql_test');
    }

    public function run()
    {
        $this->databaseConnection()->table('system_window')->insert(
            $this->for_app_manager()
        );

        $this->databaseConnection()->table('system_window')->insert(
            $this->for_acc_manager()
        );

        $this->databaseConnection()->table('system_window')->insert(
            $this->for_inventory_system()
        );
    }

    protected function for_app_manager()
    {
        return array(
            array(
                "menu_id" => 18,
                "module_id" => 1,
                "menu_parent" => 0,
                "menu_name" => "App Windows",
                "menu_path" => "window",
                "menu_level" => 1,
                "menu_icon" => "fa fa-windows",
                "menu_trait" => "SystemWindowLoaderTrait",
                "menu_method" => "settings_window",
                "menu_blade" => "manage.system.settings.SystemWindow",
                "menu_type" => 0,
                "menu_status" => 1,
                "order_level" => 4,
            ),
            array(
                "menu_id" => 219,
                "module_id" => 1,
                "menu_parent" => 0,
                "menu_name" => "Method & Action",
                "menu_path" => "methods",
                "menu_level" => 1,
                "menu_icon" => "fa fa-dropbox",
                "menu_trait" => "SystemWindowLoaderTrait",
                "menu_method" => "settings_method",
                "menu_blade" => "manage.system.settings.SystemMethod",
                "menu_type" => 0,
                "menu_status" => 1,
                "order_level" => 5,
            ),
            array(
                "menu_id" => 138,
                "module_id" => 1,
                "menu_parent" => 0,
                "menu_name" => "App Modules",
                "menu_path" => "modules",
                "menu_level" => 1,
                "menu_icon" => "fa fa-table",
                "menu_trait" => "SystemWindowLoaderTrait",
                "menu_method" => "settings_module",
                "menu_blade" => "manage.system.settings.SystemModule",
                "menu_type" => 0,
                "menu_status" => 1,
                "order_level" => 3,
            ),
            array(
                "menu_id" => 137,
                "module_id" => 1,
                "menu_parent" => 0,
                "menu_name" => "Dashboard",
                "menu_path" => "home",
                "menu_level" => 1,
                "menu_icon" => "fa fa-dashboard",
                "menu_trait" => "SystemWindowLoaderTrait",
                "menu_method" => "settings_dashboard",
                "menu_blade" => "manage.system.settings.SystemDashboard",
                "menu_type" => 0,
                "menu_status" => 1,
                "order_level" => 1,
            ),
            array(
                "menu_id" => 131,
                "module_id" => 1,
                "menu_parent" => 0,
                "menu_name" => "DB Backup",
                "menu_path" => "database-backup",
                "menu_level" => 1,
                "menu_icon" => "fa fa-database",
                "menu_trait" => "SystemWindowLoaderTrait",
                "menu_method" => "settings_database_backup",
                "menu_blade" => "manage.system.settings.SystemDatabaseBackup",
                "menu_type" => 0,
                "menu_status" => 1,
                "order_level" => 6,
            ),
            array(
                "menu_id" => 130,
                "module_id" => 1,
                "menu_parent" => 0,
                "menu_name" => "App Company",
                "menu_path" => "company",
                "menu_level" => 1,
                "menu_icon" => "fa fa-home",
                "menu_trait" => "SystemWindowLoaderTrait",
                "menu_method" => "settings_company",
                "menu_blade" => "manage.system.settings.SystemCompany",
                "menu_type" => 0,
                "menu_status" => 1,
                "order_level" => 2,
            ),
        );
    }

    protected function for_acc_manager()
    {
        return array(
            array(
                "menu_id" => 223,
                "module_id" => 2,
                "menu_parent" => 0,
                "menu_name" => "Users Window",
                "menu_path" => "users-window",
                "menu_level" => 1,
                "menu_icon" => "fa fa-folder-o",
                "menu_trait" => "UsersWindowLoaderTrait",
                "menu_method" => "accounts_users_window_access",
                "menu_blade" => "manage.system.accounts.UsersWindowAccess",
                "menu_type" => 0,
                "menu_status" => 1,
                "order_level" => NULL,
            ),
            array(
                "menu_id" => 216,
                "module_id" => 2,
                "menu_parent" => 0,
                "menu_name" => "Profile",
                "menu_path" => "users-profile",
                "menu_level" => 1,
                "menu_icon" => "fa fa-user",
                "menu_trait" => "UsersWindowLoaderTrait",
                "menu_method" => "accounts_users_profile",
                "menu_blade" => "manage.system.accounts.UsersProfile",
                "menu_type" => 0,
                "menu_status" => 1,
                "order_level" => NULL,
            ),
            array(
                "menu_id" => 215,
                "module_id" => 2,
                "menu_parent" => 0,
                "menu_name" => "Dashboard",
                "menu_path" => "home",
                "menu_level" => 1,
                "menu_icon" => "fa fa-dashboard",
                "menu_trait" => "UsersWindowLoaderTrait",
                "menu_method" => "accounts_dashboard",
                "menu_blade" => "manage.system.accounts.UsersDashboard",
                "menu_type" => 0,
                "menu_status" => 1,
                "order_level" => NULL,
            ),
            array(
                "menu_id" => 127,
                "module_id" => 2,
                "menu_parent" => 0,
                "menu_name" => "Users Table",
                "menu_path" => "users",
                "menu_level" => 1,
                "menu_icon" => "fa fa-users",
                "menu_trait" => "UsersWindowLoaderTrait",
                "menu_method" => "accounts_users",
                "menu_blade" => "manage.system.accounts.Users",
                "menu_type" => 0,
                "menu_status" => 1,
                "order_level" => NULL,
            ),
        );
    }

    protected function for_inventory_system()
    {
        return array(
            array(
                "menu_id" => 242,
                "module_id" => 2,
                "menu_parent" => 0,
                "menu_name" => "Department",
                "menu_path" => "department",
                "menu_level" => 1,
                "menu_icon" => "fa fa-circle-o",
                "menu_trait" => "InventoryWindowLoaderTrait",
                "menu_method" => "inventory_department",
                "menu_blade" => "manage.inventory.maintenance.InventoryDepartment",
                "menu_type" => 0,
                "menu_status" => 1,
                "order_level" => 18,
            ),
            array(
                "menu_id" => 244,
                "module_id" => 2,
                "menu_parent" => 0,
                "menu_name" => "Warehouse",
                "menu_path" => "warehouse",
                "menu_level" => 1,
                "menu_icon" => "fa fa-circle-o",
                "menu_trait" => "InventoryWindowLoaderTrait",
                "menu_method" => "inventory_warehouse",
                "menu_blade" => "manage.inventory.maintenance.InventoryWarehouse",
                "menu_type" => 0,
                "menu_status" => 1,
                "order_level" => 17,
            ),
            array(
                "menu_id" => 245,
                "module_id" => 2,
                "menu_parent" => 0,
                "menu_name" => "Unit of Measure",
                "menu_path" => "unit-of-measurement",
                "menu_level" => 1,
                "menu_icon" => "fa fa-circle-o",
                "menu_trait" => "InventoryWindowLoaderTrait",
                "menu_method" => "inventory_unit_measure",
                "menu_blade" => "manage.inventory.maintenance.InventoryUnitMeasure",
                "menu_type" => 0,
                "menu_status" => 1,
                "order_level" => 16,
            ),
            array(
                "menu_id" => 246,
                "module_id" => 2,
                "menu_parent" => 0,
                "menu_name" => "Variation",
                "menu_path" => "variation",
                "menu_level" => 1,
                "menu_icon" => "fa fa-circle-o",
                "menu_trait" => "InventoryWindowLoaderTrait",
                "menu_method" => "inventory_variation",
                "menu_blade" => "manage.inventory.maintenance.InventoryVariation",
                "menu_type" => 0,
                "menu_status" => 0,
                "order_level" => NULL,
            ),
            array(
                "menu_id" => 248,
                "module_id" => 2,
                "menu_parent" => 0,
                "menu_name" => "Address",
                "menu_path" => "address",
                "menu_level" => 1,
                "menu_icon" => "fa fa-circle-o",
                "menu_trait" => "InventoryWindowLoaderTrait",
                "menu_method" => "inventory_address",
                "menu_blade" => "manage.inventory.maintenance.InventoryAddress",
                "menu_type" => 0,
                "menu_status" => 1,
                "order_level" => NULL,
            ),
            array(
                "menu_id" => 249,
                "module_id" => 2,
                "menu_parent" => 0,
                "menu_name" => "Contacts",
                "menu_path" => "contacts",
                "menu_level" => 1,
                "menu_icon" => "fa fa-circle-o",
                "menu_trait" => "InventoryWindowLoaderTrait",
                "menu_method" => "inventory_contact",
                "menu_blade" => "manage.inventory.maintenance.InventoryContact",
                "menu_type" => 0,
                "menu_status" => 1,
                "order_level" => NULL,
            ),
            array(
                "menu_id" => 251,
                "module_id" => 2,
                "menu_parent" => 0,
                "menu_name" => "Supplier",
                "menu_path" => "supplier",
                "menu_level" => 1,
                "menu_icon" => "fa fa-circle-o",
                "menu_trait" => "InventoryWindowLoaderTrait",
                "menu_method" => "inventory_supplier",
                "menu_blade" => "manage.inventory.maintenance.InventorySupplier",
                "menu_type" => 0,
                "menu_status" => 1,
                "order_level" => 14,
            ),
            array(
                "menu_id" => 252,
                "module_id" => 2,
                "menu_parent" => 0,
                "menu_name" => "Sales",
                "menu_path" => "sales",
                "menu_level" => 1,
                "menu_icon" => "fa fa-circle-o",
                "menu_trait" => NULL,
                "menu_method" => NULL,
                "menu_blade" => NULL,
                "menu_type" => 1,
                "menu_status" => 1,
                "order_level" => 2,
            ),
            array(
                "menu_id" => 256,
                "module_id" => 2,
                "menu_parent" => 0,
                "menu_name" => "Inventory",
                "menu_path" => "inventory",
                "menu_level" => 1,
                "menu_icon" => "fa fa-circle-o",
                "menu_trait" => NULL,
                "menu_method" => NULL,
                "menu_blade" => NULL,
                "menu_type" => 1,
                "menu_status" => 1,
                "order_level" => 5,
            ),
            array(
                "menu_id" => 253,
                "module_id" => 2,
                "menu_parent" => 252,
                "menu_name" => "Sales Order",
                "menu_path" => "sales-order",
                "menu_level" => 2,
                "menu_icon" => "fa fa-circle-o",
                "menu_trait" => "InventoryWindowLoaderTrait",
                "menu_method" => "inventory_order",
                "menu_blade" => "manage.inventory.activity.InventoryOrder",
                "menu_type" => 0,
                "menu_status" => 1,
                "order_level" => 4,
            ),
            array(
                "menu_id" => 254,
                "module_id" => 2,
                "menu_parent" => 0,
                "menu_name" => "Customer",
                "menu_path" => "customer",
                "menu_level" => 1,
                "menu_icon" => "fa fa-circle-o",
                "menu_trait" => "InventoryWindowLoaderTrait",
                "menu_method" => "inventory_customer",
                "menu_blade" => "manage.inventory.maintenance.InventoryCustomer",
                "menu_type" => 0,
                "menu_status" => 1,
                "order_level" => 15,
            ),
            array(
                "menu_id" => 255,
                "module_id" => 2,
                "menu_parent" => 252,
                "menu_name" => "Sales Cashier",
                "menu_path" => "sales-cashier",
                "menu_level" => 2,
                "menu_icon" => "fa fa-circle-o",
                "menu_trait" => "InventoryWindowLoaderTrait",
                "menu_method" => "inventory_cashier",
                "menu_blade" => "manage.inventory.activity.InventoryCashier",
                "menu_type" => 0,
                "menu_status" => 1,
                "order_level" => 3,
            ),
            array(
                "menu_id" => 240,
                "module_id" => 2,
                "menu_parent" => 0,
                "menu_name" => "Item Group",
                "menu_path" => "product-group",
                "menu_level" => 1,
                "menu_icon" => "fa fa-circle-o",
                "menu_trait" => "InventoryWindowLoaderTrait",
                "menu_method" => "inventory_product_group",
                "menu_blade" => "manage.inventory.maintenance.InventoryProductGroup",
                "menu_type" => 0,
                "menu_status" => 1,
                "order_level" => 13,
            ),
            array(
                "menu_id" => 239,
                "module_id" => 2,
                "menu_parent" => 0,
                "menu_name" => "Item",
                "menu_path" => "product",
                "menu_level" => 1,
                "menu_icon" => "fa fa-circle-o",
                "menu_trait" => "InventoryWindowLoaderTrait",
                "menu_method" => "inventory_product",
                "menu_blade" => "manage.inventory.maintenance.InventoryProduct",
                "menu_type" => 0,
                "menu_status" => 1,
                "order_level" => 12,
            ),
            array(
                "menu_id" => 225,
                "module_id" => 2,
                "menu_parent" => 0,
                "menu_name" => "Dashboard",
                "menu_path" => "home",
                "menu_level" => 1,
                "menu_icon" => "fa fa-circle-o",
                "menu_trait" => "InventoryWindowLoaderTrait",
                "menu_method" => "inventory_dashboard",
                "menu_blade" => "manage.inventory.dashboard.InventoryDashboard",
                "menu_type" => 0,
                "menu_status" => 1,
                "order_level" => 1,
            ),
            array(
                "menu_id" => 229,
                "module_id" => 2,
                "menu_parent" => 0,
                "menu_name" => "Maintenance",
                "menu_path" => "maintenance",
                "menu_level" => 1,
                "menu_icon" => "fa fa-circle-o",
                "menu_trait" => "InventoryWindowLoaderTrait",
                "menu_method" => NULL,
                "menu_blade" => NULL,
                "menu_type" => 0,
                "menu_status" => 1,
                "order_level" => 11,
            ),
            array(
                "menu_id" => 231,
                "module_id" => 2,
                "menu_parent" => 0,
                "menu_name" => "Report",
                "menu_path" => "report",
                "menu_level" => 1,
                "menu_icon" => "fa fa-circle-o",
                "menu_trait" => "InventoryWindowLoaderTrait",
                "menu_method" => "inventory_reports",
                "menu_blade" => "manage.inventory.report.InventoryReport",
                "menu_type" => 0,
                "menu_status" => 1,
                "order_level" => 19,
            ),
            array(
                "menu_id" => 233,
                "module_id" => 2,
                "menu_parent" => 0,
                "menu_name" => "Issuance",
                "menu_path" => "issuance",
                "menu_level" => 1,
                "menu_icon" => "fa fa-circle-o",
                "menu_trait" => "InventoryWindowLoaderTrait",
                "menu_method" => "inventory_issuance",
                "menu_blade" => "manage.inventory.activity.InventoryIssuance",
                "menu_type" => 0,
                "menu_status" => 1,
                "order_level" => 6,
            ),
            array(
                "menu_id" => 235,
                "module_id" => 2,
                "menu_parent" => 0,
                "menu_name" => "Issuance Return",
                "menu_path" => "issuance-return",
                "menu_level" => 1,
                "menu_icon" => "fa fa-circle-o",
                "menu_trait" => "InventoryWindowLoaderTrait",
                "menu_method" => "inventory_issuance_retrun",
                "menu_blade" => "manage.inventory.activity.InventoryIssuanceReturn",
                "menu_type" => 0,
                "menu_status" => 1,
                "order_level" => 7,
            ),
            array(
                "menu_id" => 236,
                "module_id" => 2,
                "menu_parent" => 0,
                "menu_name" => "Stock Transfer",
                "menu_path" => "stock-transfer",
                "menu_level" => 1,
                "menu_icon" => "fa fa-circle-o",
                "menu_trait" => "InventoryWindowLoaderTrait",
                "menu_method" => "inventory_stock_transfer",
                "menu_blade" => "manage.inventory.activity.InventoryStockTransfer",
                "menu_type" => 0,
                "menu_status" => 1,
                "order_level" => 8,
            ),
            array(
                "menu_id" => 238,
                "module_id" => 2,
                "menu_parent" => 0,
                "menu_name" => "Product List",
                "menu_path" => "product-listing",
                "menu_level" => 1,
                "menu_icon" => "fa fa-circle-o",
                "menu_trait" => "InventoryWindowLoaderTrait",
                "menu_method" => "inventory_product_listing",
                "menu_blade" => "manage.inventory.activity.InventoryProductList",
                "menu_type" => 0,
                "menu_status" => 1,
                "order_level" => 9,
            ),
            array(
                "menu_id" => 258,
                "module_id" => 3,
                "menu_parent" => 256,
                "menu_name" => "Physical Count",
                "menu_path" => "physical-count",
                "menu_level" => 1,
                "menu_icon" => "fa fa-circle-o",
                "menu_trait" => "InventoryWindowLoaderTrait",
                "menu_method" => "inventory_physical_count",
                "menu_blade" => NULL,
                "menu_type" => 0,
                "menu_status" => 1,
                "order_level" => 10,
            ),
        );
    }
}
