<?php

use Illuminate\Database\Seeder;

class SystemCompanyWindowMethodSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    protected function databaseConnection()
    {
        return DB::connection('mysql');
    }

    public function run()
    {
        $this->databaseConnection()->table('system_window_method')->insert(
            $this->for_app_manager()
        );

        $this->databaseConnection()->table('system_window_method')->insert(
            $this->for_acc_manager()
        );

        $this->databaseConnection()->table('system_window_method')->insert(
            $this->for_inventory_system()
        );
    }

    protected function for_app_manager()
    {
        return array(
            array(
                "window_method_code" => 'APP00001',
                "window_method_window_code" => 'APP00004',
                "window_method_module_id" => 1,
                "window_method_name" => "search-module-window-json-data",
                "window_method_request" => "get",
                "window_method_blade" => NULL,
                "window_method_action" => "settings_search_module_window_data",
                "window_method_traits" => "SystemMethodLoaderTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-07-10 00:00:00",
            ),
            array(
                "window_method_code" => 'APP00002',
                "window_method_window_code" => 'APP00004',
                "window_method_module_id" => 1,
                "window_method_name" => "search-module-window-json",
                "window_method_request" => "get",
                "window_method_blade" => "manage.system.settings.includes.TableSystemWindow",
                "window_method_action" => "settings_search_module_window",
                "window_method_traits" => "SystemMethodLoaderTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-07-10 00:00:00",
            ),
            array(
                "window_method_code" => 'APP00003',
                "window_method_window_code" => 'APP00004',
                "window_method_module_id" => 1,
                "window_method_name" => "create-window-method",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "settings_create_window_method",
                "window_method_traits" => "SystemWindowMethodTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-05-03 00:00:00",
            ),
            array(
                "window_method_code" => 'APP00004',
                "window_method_window_code" => 'APP00004',
                "window_method_module_id" => 1,
                "window_method_name" => "create-system-window",
                "window_method_request" => "get",
                "window_method_blade" => NULL,
                "window_method_action" => "settings_create_system_window",
                "window_method_traits" => "SystemWindowTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-05-03 00:00:00",
            ),
            array(
                "window_method_code" => 'APP00005',
                "window_method_window_code" => 'APP00004',
                "window_method_module_id" => 1,
                "window_method_name" => "update-system-window",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "settings_update_system_window",
                "window_method_traits" => "SystemWindowTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-07-10 00:00:00",
            ),
            array(
                "window_method_code" => 'APP00006',
                "window_method_window_code" => 'APP00004',
                "window_method_module_id" => 1,
                "window_method_name" => "delete-system-window",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "settings_delete_system_window",
                "window_method_traits" => "SystemWindowTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-05-03 00:00:00",
            ),
            array(
                "window_method_code" => 'APP00007',
                "window_method_window_code" => 'APP00004',
                "window_method_module_id" => 1,
                "window_method_name" => "retrieve-window-sub",
                "window_method_request" => "get",
                "window_method_blade" => NULL,
                "window_method_action" => "settings_retrieve_window_sub_class",
                "window_method_traits" => "UsersCollectionModifierTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-05-03 00:00:00",
            ),
            array(
                "window_method_code" => 'APP00008',
                "window_method_window_code" => 'APP00004',
                "window_method_module_id" => 1,
                "window_method_name" => "retrieve-window",
                "window_method_request" => "get",
                "window_method_blade" => NULL,
                "window_method_action" => "settings_retrieve_active_windows",
                "window_method_traits" => "UsersCollectionModifierTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-05-03 00:00:00",
            ),
            array(
                "window_method_code" => 'APP00009',
                "window_method_window_code" => 'APP00004',
                "window_method_module_id" => 1,
                "window_method_name" => "search-system-window",
                "window_method_request" => "post",
                "window_method_blade" => "manage.settings.includes.systemwindowtable",
                "window_method_action" => "settings_search_system_window",
                "window_method_traits" => "UsersCollectionModifierTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2019-12-27 00:00:00",
            ),
            array(
                "window_method_code" => 'APP00010',
                "window_method_window_code" => 'APP00004',
                "window_method_module_id" => 1,
                "window_method_name" => "retrieve-window-method",
                "window_method_request" => "get",
                "window_method_blade" => NULL,
                "window_method_action" => "settings_retrieve_window_classes",
                "window_method_traits" => "UsersCollectionModifierTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-05-03 00:00:00",
            ),
            array(
                "window_method_code" => 'APP00011',
                "window_method_window_code" => 'APP00004',
                "window_method_module_id" => 1,
                "window_method_name" => "update-window-method",
                "window_method_request" => "post",
                "window_method_blade" => "manage.settings.includes.usersmethodaccesstable",
                "window_method_action" => "settings_update_users_method_access",
                "window_method_traits" => "UsersWindowMethodAccessTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2019-12-23 00:00:00",
            ),
            array(
                "window_method_code" => 'APP00012',
                "window_method_window_code" => "APP00002",
                "window_method_module_id" => 1,
                "window_method_name" => "update-company-module",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "settings_update_company_module_access",
                "window_method_traits" => "SystemCompanyModuleAccessTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2019-12-27 00:00:00",
            ),
            array(
                "window_method_code" => "APP00013",
                "window_method_window_code" => "APP00002",
                "window_method_module_id" => 1,
                "window_method_name" => "update-system-company",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "settings_update_system_company",
                "window_method_traits" => "SystemCompanyTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-07-26 00:00:00",
            ),
            array(
                "window_method_code" => "APP00014",
                "window_method_window_code" => "APP00002",
                "window_method_module_id" => 1,
                "window_method_name" => "create-system-company",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "settings_create_system_company",
                "window_method_traits" => "SystemCompanyTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-07-26 00:00:00",
            ),
            array(
                "window_method_code" => "APP00015",
                "window_method_window_code" => "APP00002",
                "window_method_module_id" => 1,
                "window_method_name" => "toggle-system-company",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "settings_toggle_system_company",
                "window_method_traits" => "SystemCompanyTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-07-26 00:00:00",
            ),
            array(
                "window_method_code" => "APP00016",
                "window_method_window_code" => "APP00002",
                "window_method_module_id" => 1,
                "window_method_name" => "delete-system-company",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "settings_delete_system_company",
                "window_method_traits" => "SystemCompanyTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-05-03 00:00:00",
            ),
            array(
                "window_method_code" => "APP00017",
                "window_method_window_code" => "APP00002",
                "window_method_module_id" => 1,
                "window_method_name" => "edit-system-company",
                "window_method_request" => "get",
                "window_method_blade" => "manage.system.settings.SystemEditCompany",
                "window_method_action" => "settings_edit_system_company",
                "window_method_traits" => "SystemMethodLoaderTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-05-03 00:00:00",
            ),
            array(
                "window_method_code" => "APP00018",
                "window_method_window_code" => "APP00002",
                "window_method_module_id" => 1,
                "window_method_name" => "search-company-module",
                "window_method_request" => "post",
                "window_method_blade" => "manage.settings.includes.companymoduleaccesstable",
                "window_method_action" => "settings_search_company_module",
                "window_method_traits" => "UsersCollectionModifierTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-01-07 00:00:00",
            ),
            array(
                "window_method_code" => "APP00019",
                "window_method_window_code" => "APP00002",
                "window_method_module_id" => 1,
                "window_method_name" => "retrieve-company-users",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "settings_retrieve_company_users",
                "window_method_traits" => "UsersCollectionModifierTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2019-12-27 00:00:00",
            ),
            array(
                "window_method_code" => "APP00020",
                "window_method_window_code" => "APP00002",
                "window_method_module_id" => 1,
                "window_method_name" => "retrieve-company",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "settings_retrieve_company_users",
                "window_method_traits" => "UsersCollectionModifierTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2019-12-27 00:00:00",
            ),
            array(
                "window_method_code" => "APP00021",
                "window_method_window_code" => "APP00002",
                "window_method_module_id" => 1,
                "window_method_name" => "update-company",
                "window_method_request" => "post",
                "window_method_blade" => "manage.settings.includes.userscompanyaccesstable",
                "window_method_action" => "settings_update_users_company_access",
                "window_method_traits" => "UsersCompanyAccessTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2019-12-27 00:00:00",
            ),
            array(
                "window_method_code" => "APP00022",
                "window_method_window_code" => "APP00003",
                "window_method_module_id" => 1,
                "window_method_name" => "edit-system-module",
                "window_method_request" => "get",
                "window_method_blade" => "manage.system.settings.SystemEditModule",
                "window_method_action" => "settings_edit_system_module",
                "window_method_traits" => "SystemMethodLoaderTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-07-27 00:00:00",
            ),
            array(
                "window_method_code" => "APP00023",
                "window_method_window_code" => "APP00003",
                "window_method_module_id" => 1,
                "window_method_name" => "toggle-system-module",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "settings_toggle_system_module",
                "window_method_traits" => "SystemModuleTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-01-07 00:00:00",
            ),
            array(
                "window_method_code" => "APP00024",
                "window_method_window_code" => "APP00003",
                "window_method_module_id" => 1,
                "window_method_name" => "update-system-module",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "settings_update_system_module",
                "window_method_traits" => "SystemModuleTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-01-07 00:00:00",
            ),
            array(
                "window_method_code" => "APP00025",
                "window_method_window_code" => "APP00003",
                "window_method_module_id" => 1,
                "window_method_name" => "delete-system-module",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "settings_delete_system_module",
                "window_method_traits" => "SystemModuleTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-01-07 00:00:00",
            ),
            array(
                "window_method_code" => "APP00026",
                "window_method_window_code" => "APP00003",
                "window_method_module_id" => 1,
                "window_method_name" => "create-system-module",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "settings_create_system_module",
                "window_method_traits" => "SystemModuleTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-01-07 00:00:00",
            ),
            array(
                "window_method_code" => "APP00027",
                "window_method_window_code" => "APP00003",
                "window_method_module_id" => 1,
                "window_method_name" => "retrieve-module",
                "window_method_request" => "get",
                "window_method_blade" => NULL,
                "window_method_action" => "settings_retrieve_users_module",
                "window_method_traits" => "UsersCollectionModifierTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2019-12-22 00:00:00",
            ),
            // array(
            //     "window_method_window_code" => 218,
            //     "window_method_module_id" => 1,
            //     "window_method_name" => "update-image-content",
            //     "window_method_request" => "post",
            //     "window_method_blade" => NULL,
            //     "window_method_action" => "update_image_content",
            //     "window_method_traits" => "SystemMediaUploaderTrait",
            //     "window_method_type" => "common",
            //     "status" => 1,
            //     "order_level" => NULL,
            //     "created_by" => 1,
            //     "created_date" => "2020-07-25 00:00:00",
            // ),
            // array(
            //     "window_method_window_code" => 218,
            //     "window_method_module_id" => 1,
            //     "window_method_name" => "retrieve-images",
            //     "window_method_request" => "post",
            //     "window_method_blade" => "manage.common.includes.SelectUploadedImage",
            //     "window_method_action" => "get_uploaded_image",
            //     "window_method_traits" => "SystemMediaUploaderTrait",
            //     "window_method_type" => "common",
            //     "status" => 1,
            //     "order_level" => NULL,
            //     "created_by" => 1,
            //     "created_date" => "2020-07-22 00:00:00",
            // ),
            // array(
            //     "window_method_window_code" => 218,
            //     "window_method_module_id" => 1,
            //     "window_method_name" => "upload-image-content",
            //     "window_method_request" => "post",
            //     "window_method_blade" => NULL,
            //     "window_method_action" => "upload_image_content",
            //     "window_method_traits" => "SystemMediaUploaderTrait",
            //     "window_method_type" => "common",
            //     "status" => 1,
            //     "order_level" => NULL,
            //     "created_by" => 1,
            //     "created_date" => "2020-07-22 00:00:00",
            // ),
        );
    }

    protected function for_acc_manager()
    {
        return array(
            array(
                "window_method_code" => "ACC00001",
                "window_method_window_code" => "ACC00002",
                "window_method_module_id" => 2,
                "window_method_name" => "update-users-window-method",
                "window_method_request" => "post",
                "window_method_blade" => "manage.system.accounts.includes.TableUsersWindowMethodAccess",
                "window_method_action" => "accounts_update_users_window_method_access",
                "window_method_traits" => "UsersAccessAccountTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-05-03 00:00:00",
            ),
            array(
                "window_method_code" => "ACC00002",
                "window_method_window_code" => "ACC00002",
                "window_method_module_id" => 2,
                "window_method_name" => "update-users-information",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "accounts_update_users_information",
                "window_method_traits" => "UsersAccessAccountTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-07-26 00:00:00",
            ),
            array(
                "window_method_code" => "ACC00003",
                "window_method_window_code" => "ACC00002",
                "window_method_module_id" => 2,
                "window_method_name" => "update-users-company",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "accounts_update_users_company_access",
                "window_method_traits" => "UsersAccessAccountTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2019-12-27 00:00:00",
            ),
            array(
                "window_method_code" => "ACC00004",
                "window_method_window_code" => "ACC00002",
                "window_method_module_id" => 2,
                "window_method_name" => "update-users-password",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "accounts_update_users_password",
                "window_method_traits" => "UsersAccessAccountTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-07-26 00:00:00",
            ),
            array(
                "window_method_code" => "ACC00005",
                "window_method_window_code" => "ACC00002",
                "window_method_module_id" => 2,
                "window_method_name" => "toggle-users-profile",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "accounts_toggle_users_account",
                "window_method_traits" => "UsersAccessAccountTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-05-02 00:00:00",
            ),
            array(
                "window_method_code" => "ACC00006",
                "window_method_window_code" => "ACC00002",
                "window_method_module_id" => 2,
                "window_method_name" => "create-users-account",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "accounts_create_users_account",
                "window_method_traits" => "UsersAccessAccountTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-06-23 00:00:00",
            ),
            array(
                "window_method_code" => "ACC00007",
                "window_method_window_code" => "ACC00002",
                "window_method_module_id" => 2,
                "window_method_name" => "update-users-profile-photo",
                "window_method_request" => "post",
                "window_method_blade" => "manage.system.accounts.UsersProfile",
                "window_method_action" => "accounts_update_users_profile_photo",
                "window_method_traits" => "UsersAccessAccountTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-05-02 00:00:00",
            ),
            array(
                "window_method_code" => "ACC00008",
                "window_method_window_code" => "ACC00002",
                "window_method_module_id" => 2,
                "window_method_name" => "update-users-module",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "accounts_update_users_module_access",
                "window_method_traits" => "UsersAccessModuleTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2019-12-27 00:00:00",
            ),
            array(
                "window_method_code" => "ACC00009",
                "window_method_window_code" => "ACC00002",
                "window_method_module_id" => 2,
                "window_method_name" => "update-users-window",
                "window_method_request" => "post",
                "window_method_blade" => "manage.system.accounts.includes.TableUsersWindowAccess",
                "window_method_action" => "accounts_update_users_window_access",
                "window_method_traits" => "UsersAccessWindowTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-05-03 00:00:00",
            ),
            array(
                "window_method_code" => "ACC00010",
                "window_method_window_code" => "ACC00002",
                "window_method_module_id" => 2,
                "window_method_name" => "search-company-module",
                "window_method_request" => "get",
                "window_method_blade" => "manage.system.accounts.includes.TableUsersModuleAccess",
                "window_method_action" => "accounts_search_company_module_table",
                "window_method_traits" => "UsersCollectionModifierTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-05-02 00:00:00",
            ),
            array(
                "window_method_code" => "ACC00011",
                "window_method_window_code" => "ACC00002",
                "window_method_module_id" => 2,
                "window_method_name" => "search-users-module-json",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "accounts_search_users_module_json",
                "window_method_traits" => "UsersCollectionModifierTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-07-29 00:00:00",
            ),
            array(
                "window_method_code" => "ACC00012",
                "window_method_window_code" => "ACC00002",
                "window_method_module_id" => 2,
                "window_method_name" => "search-users-window-json",
                "window_method_request" => "get",
                "window_method_blade" => NULL,
                "window_method_action" => "accounts_search_users_window_json",
                "window_method_traits" => "UsersCollectionModifierTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-07-29 00:00:00",
            ),
            array(
                "window_method_code" => "ACC00013",
                "window_method_window_code" => "ACC00002",
                "window_method_module_id" => 2,
                "window_method_name" => "search-users-company-module-json",
                "window_method_request" => "get",
                "window_method_blade" => NULL,
                "window_method_action" => "accounts_search_users_company_module_json",
                "window_method_traits" => "UsersCollectionModifierTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-06-23 00:00:00",
            ),
            array(
                "window_method_code" => "ACC00014",
                "window_method_window_code" => "ACC00002",
                "window_method_module_id" => 2,
                "window_method_name" => "search-users-company-table",
                "window_method_request" => "post",
                "window_method_blade" => "manage.system.accounts.includes.TableUsersCompanyAccess",
                "window_method_action" => "accounts_search_users_company_table",
                "window_method_traits" => "UsersMethodLoaderTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2019-12-27 00:00:00",
            ),
            array(
                "window_method_code" => "ACC00015",
                "window_method_window_code" => "ACC00002",
                "window_method_module_id" => 2,
                "window_method_name" => "search-company-users-table",
                "window_method_request" => "post",
                "window_method_blade" => "manage.system.accounts.includes.TableUsersAccount",
                "window_method_action" => "accounts_search_company_users_table",
                "window_method_traits" => "UsersMethodLoaderTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-06-23 00:00:00",
            ),
            array(
                "window_method_code" => "ACC00016",
                "window_method_window_code" => "ACC00002",
                "window_method_module_id" => 2,
                "window_method_name" => "search-users-window-table",
                "window_method_request" => "post",
                "window_method_blade" => "manage.system.accounts.includes.TableUsersWindowAccess",
                "window_method_action" => "accounts_search_users_window_table",
                "window_method_traits" => "UsersMethodLoaderTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2019-12-22 00:00:00",
            ),
            array(
                "window_method_code" => "ACC00017",
                "window_method_window_code" => "ACC00002",
                "window_method_module_id" => 2,
                "window_method_name" => "users-profile",
                "window_method_request" => "get",
                "window_method_blade" => "manage.system.accounts.UsersProfile",
                "window_method_action" => "accounts_users_user_profile",
                "window_method_traits" => "UsersMethodLoaderTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-05-02 00:00:00",
            ),
            array(
                "window_method_code" => "ACC00018",
                "window_method_window_code" => "ACC00002",
                "window_method_module_id" => 2,
                "window_method_name" => "users-company",
                "window_method_request" => "get",
                "window_method_blade" => "manage.system.accounts.UsersCompany",
                "window_method_action" => "accounts_users_user_company",
                "window_method_traits" => "UsersMethodLoaderTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-05-02 00:00:00",
            ),
            array(
                "window_method_code" => "ACC00019",
                "window_method_window_code" => "ACC00002",
                "window_method_module_id" => 2,
                "window_method_name" => "search-users-window-method-table",
                "window_method_request" => "post",
                "window_method_blade" => "manage.system.accounts.includes.TableUsersWindowMethodAccess",
                "window_method_action" => "accounts_search_users_window_method_table",
                "window_method_traits" => "UsersMethodLoaderTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-07-29 00:00:00",
            ),
            array(
                "window_method_code" => "ACC00020",
                "window_method_window_code" => "ACC00002",
                "window_method_module_id" => 2,
                "window_method_name" => "users-window",
                "window_method_request" => "get",
                "window_method_blade" => "manage.system.accounts.UsersWindow",
                "window_method_action" => "accounts_users_user_window",
                "window_method_traits" => "UsersMethodLoaderTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-05-02 00:00:00",
            ),
            array(
                "window_method_code" => "ACC00021",
                "window_method_window_code" => "ACC00002",
                "window_method_module_id" => 2,
                "window_method_name" => "search-users-module-table",
                "window_method_request" => "post",
                "window_method_blade" => "manage.system.accounts.includes.TableUsersModuleAccess",
                "window_method_action" => "accounts_search_users_module_table",
                "window_method_traits" => "UsersMethodLoaderTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-07-29 00:00:00",
            ),
            array(
                "window_method_code" => "ACC00022",
                "window_method_window_code" => "ACC00002",
                "window_method_module_id" => 2,
                "window_method_name" => "users-method",
                "window_method_request" => "get",
                "window_method_blade" => "manage.system.accounts.UsersMethod",
                "window_method_action" => "accounts_users_user_method",
                "window_method_traits" => "UsersMethodLoaderTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-05-02 00:00:00",
            ),
            array(
                "window_method_code" => "ACC00023",
                "window_method_window_code" => "ACC00002",
                "window_method_module_id" => 2,
                "window_method_name" => "users-module",
                "window_method_request" => "get",
                "window_method_blade" => "manage.system.accounts.UsersModule",
                "window_method_action" => "accounts_users_user_module",
                "window_method_traits" => "UsersMethodLoaderTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-05-02 00:00:00",
            ),
            array(
                "window_method_code" => "ACC00024",
                "window_method_window_code" => "ACC00004",
                "window_method_module_id" => 2,
                "window_method_name" => "update-users-profile-photo",
                "window_method_request" => "post",
                "window_method_blade" => "manage.system.accounts.UsersProfile",
                "window_method_action" => "accounts_update_users_profile_photo",
                "window_method_traits" => "UsersAccessAccountTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-05-02 00:00:00",
            ),
            array(
                "window_method_code" => "ACC00025",
                "window_method_window_code" => "ACC00004",
                "window_method_module_id" => 2,
                "window_method_name" => "update-users-password",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "accounts_update_users_password",
                "window_method_traits" => "UsersAccessAccountTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-07-26 00:00:00",
            ),
            array(
                "window_method_code" => "ACC00026",
                "window_method_window_code" => "ACC00004",
                "window_method_module_id" => 2,
                "window_method_name" => "update-users-information",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "accounts_update_users_information",
                "window_method_traits" => "UsersAccessAccountTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-07-26 00:00:00",
            ),
            array(
                "window_method_code" => "ACC00027",
                "window_method_window_code" => "ACC00004",
                "window_method_module_id" => 2,
                "window_method_name" => "update-users-window-access",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "accounts_update_users_window_access_reorder",
                "window_method_traits" => "UsersAccessWindowTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-08-23 00:00:00",
            ),
            array(
                "window_method_code" => "ACC00028",
                "window_method_window_code" => "ACC00004",
                "window_method_module_id" => 2,
                "window_method_name" => "delete-users-window-access",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "accounts_delete_users_window_access",
                "window_method_traits" => "UsersAccessWindowTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-08-23 00:00:00",
            ),
        );
    }

    protected function for_inventory_system()
    {
        return array(
            array(
                "window_method_code" => "INV00001",
                "window_method_window_code" => "INV00015",
                "window_method_module_id" => 3,
                "window_method_name" => "retrieve-customer-orders",
                "window_method_request" => "get",
                "window_method_blade" => "manage.inventory.dashboard.blades.productorderlisting",
                "window_method_action" => "inventory_dashboard_retrieve_orders",
                "window_method_traits" => "InventoryDashboardTrait",
                "window_method_type" => "common",
                "status" => 1,
                "order_level" => 1,
                "created_by" => 1,
                "created_date" => "2021-04-09 18:54:20",
            ),
            array(
                "window_method_code" => "INV00002",
                "window_method_window_code" => "INV00015",
                "window_method_module_id" => 3,
                "window_method_name" => "retrieve-top-customers",
                "window_method_request" => "get",
                "window_method_blade" => "manage.inventory.dashboard.blades.topcustomerlisting",
                "window_method_action" => "inventory_dashboard_retrieve_top_customers",
                "window_method_traits" => "InventoryDashboardTrait",
                "window_method_type" => "common",
                "status" => 1,
                "order_level" => 4,
                "created_by" => 1,
                "created_date" => "2021-04-09 18:54:20",
            ),
            array(
                "window_method_code" => "INV00003",
                "window_method_window_code" => "INV00015",
                "window_method_module_id" => 3,
                "window_method_name" => "retrieve-top-selling-products",
                "window_method_request" => "get",
                "window_method_blade" => "manage.inventory.dashboard.blades.topsellingproductlisting",
                "window_method_action" => "inventory_dashboard_retrieve_top_selling_products",
                "window_method_traits" => "InventoryDashboardTrait",
                "window_method_type" => "common",
                "status" => 1,
                "order_level" => 2,
                "created_by" => 1,
                "created_date" => "2021-04-09 18:54:20",
            ),
            array(
                "window_method_code" => "INV00004",
                "window_method_window_code" => "INV00015",
                "window_method_module_id" => 3,
                "window_method_name" => "retrieve-customer-cashier-details",
                "window_method_request" => "get",
                "window_method_blade" => "manage.inventory.dashboard.blades.customercashierdetails",
                "window_method_action" => "inventory_dashboard_retrieve_customer_cashier_details",
                "window_method_traits" => "InventoryDashboardTrait",
                "window_method_type" => "common",
                "status" => 1,
                "order_level" => 4,
                "created_by" => 1,
                "created_date" => "2021-04-09 18:54:20",
            ),
            array(
                "window_method_code" => "INV00005",
                "window_method_window_code" => "INV00015",
                "window_method_module_id" => 3,
                "window_method_name" => "retrieve-products-below-minimum-level",
                "window_method_request" => "get",
                "window_method_blade" => "manage.inventory.dashboard.blades.minimumlevelproductlisting",
                "window_method_action" => "inventory_dashboard_retrieve_products_below_minimum_level",
                "window_method_traits" => "InventoryDashboardTrait",
                "window_method_type" => "common",
                "status" => 1,
                "order_level" => 3,
                "created_by" => 1,
                "created_date" => "2021-04-09 18:54:20",
            ),
            array(
                "window_method_code" => "INV00006",
                "window_method_window_code" => "INV00015",
                "window_method_module_id" => 3,
                "window_method_name" => "retrieve-recent-customers",
                "window_method_request" => "get",
                "window_method_blade" => "manage.inventory.dashboard.blades.recentcustomerlisting",
                "window_method_action" => "inventory_dashboard_retrieve_recent_customers",
                "window_method_traits" => "InventoryDashboardTrait",
                "window_method_type" => "common",
                "status" => 1,
                "order_level" => 4,
                "created_by" => 1,
                "created_date" => "2021-04-09 18:54:20",
            ),
            array(
                "window_method_code" => "INV00007",
                "window_method_window_code" => "INV00015",
                "window_method_module_id" => 3,
                "window_method_name" => "retrieve-non-moving-products",
                "window_method_request" => "get",
                "window_method_blade" => "manage.inventory.dashboard.blades.nonmovingproductlisting",
                "window_method_action" => "inventory_dashboard_retrieve_non_moving_products",
                "window_method_traits" => "InventoryDashboardTrait",
                "window_method_type" => "common",
                "status" => 1,
                "order_level" => 4,
                "created_by" => 1,
                "created_date" => "2021-04-09 18:54:20",
            ),
            array(
                "window_method_code" => "INV00008",
                "window_method_window_code" => "INV00015",
                "window_method_module_id" => 3,
                "window_method_name" => "retrieve-slow-moving-products",
                "window_method_request" => "get",
                "window_method_blade" => "manage.inventory.dashboard.blades.slowmovingproductlisting",
                "window_method_action" => "inventory_dashboard_retrieve_slow_moving_products",
                "window_method_traits" => "InventoryDashboardTrait",
                "window_method_type" => "common",
                "status" => 1,
                "order_level" => 4,
                "created_by" => 1,
                "created_date" => "2021-04-09 18:54:20",
            ),
            array(
                "window_method_code" => "INV00009",
                "window_method_window_code" => "INV00015",
                "window_method_module_id" => 3,
                "window_method_name" => "retrieve-recently-added-products",
                "window_method_request" => "get",
                "window_method_blade" => "manage.inventory.dashboard.blades.recentlyaddedproductlisting",
                "window_method_action" => "inventory_dashboard_retrieve_recently_added_products",
                "window_method_traits" => "InventoryDashboardTrait",
                "window_method_type" => "common",
                "status" => 1,
                "order_level" => 4,
                "created_by" => 1,
                "created_date" => "2021-04-09 18:54:20",
            ),
            array(
                "window_method_code" => "INV00010",
                "window_method_window_code" => "INV00015",
                "window_method_module_id" => 3,
                "window_method_name" => "retrieve-out-of-stock-products",
                "window_method_request" => "get",
                "window_method_blade" => "manage.inventory.dashboard.blades.outofstockproductlisting",
                "window_method_action" => "inventory_dashboard_retrieve_out_of_stock_products",
                "window_method_traits" => "InventoryDashboardTrait",
                "window_method_type" => "common",
                "status" => 1,
                "order_level" => 4,
                "created_by" => 1,
                "created_date" => "2021-04-09 18:54:20",
            ),
            array(
                "window_method_code" => "INV00011",
                "window_method_window_code" => "INV00015",
                "window_method_module_id" => 3,
                "window_method_name" => "retrieve-products-with-expiry-date",
                "window_method_request" => "get",
                "window_method_blade" => "manage.inventory.dashboard.blades.withexpirationproductlisting",
                "window_method_action" => "inventory_dashboard_retrieve_products_with_expiry_date",
                "window_method_traits" => "InventoryDashboardTrait",
                "window_method_type" => "common",
                "status" => 1,
                "order_level" => 4,
                "created_by" => 1,
                "created_date" => "2021-04-09 18:54:20",
            ),
            array(
                "window_method_code" => "INV00012",
                "window_method_window_code" => "INV00015",
                "window_method_module_id" => 3,
                "window_method_name" => "retrieve-customer-details",
                "window_method_request" => "get",
                "window_method_blade" => "manage.inventory.dashboard.blades.customerdetails",
                "window_method_action" => "inventory_dashboard_retrieve_customer_details",
                "window_method_traits" => "InventoryDashboardTrait",
                "window_method_type" => "common",
                "status" => 1,
                "order_level" => 4,
                "created_by" => 1,
                "created_date" => "2021-04-09 18:54:20",
            ),
            array(
                "window_method_code" => "INV00013",
                "window_method_window_code" => "INV00015",
                "window_method_module_id" => 3,
                "window_method_name" => "show-product-details",
                "window_method_request" => "post",
                "window_method_blade" => "manage.inventory.dashboard.blades.productdetails",
                "window_method_action" => "inventory_show_product_details",
                "window_method_traits" => "InventoryItemTrait",
                "window_method_type" => "common",
                "status" => 1,
                "order_level" => 1,
                "created_by" => 1,
                "created_date" => "2021-01-11 00:00:00",
            ),
            array(
                "window_method_code" => "INV00014",
                "window_method_window_code" => "INV00018",
                "window_method_module_id" => 3,
                "window_method_name" => "create-issuance",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_create_issuance",
                "window_method_traits" => "InventoryIssuanceTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-09-07 00:00:00",
            ),
            array(
                "window_method_code" => "INV00015",
                "window_method_window_code" => "INV00014",
                "window_method_module_id" => 3,
                "window_method_name" => "inventory-retrieve-products-datatable",
                "window_method_request" => "get",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_retrieve_products_data",
                "window_method_traits" => "InventoryDataTableTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 4,
                "created_by" => 1,
                "created_date" => "2021-03-30 22:24:40",
            ),
            array(
                "window_method_code" => "INV00016",
                "window_method_window_code" => "INV00014",
                "window_method_module_id" => 3,
                "window_method_name" => "search-product-group",
                "window_method_request" => "get",
                "window_method_blade" => "manage.inventory.maintenance.includes.productgrouplist",
                "window_method_action" => "inventory_search_item_group",
                "window_method_traits" => "InventoryItemGroupTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-08-20 00:00:00",
            ),
            array(
                "window_method_code" => "INV00017",
                "window_method_window_code" => "INV00014",
                "window_method_module_id" => 3,
                "window_method_name" => "edit-product-details",
                "window_method_request" => "get",
                "window_method_blade" => "manage.inventory.maintenance.includes.producteditdetails",
                "window_method_action" => "inventory_show_product_details",
                "window_method_traits" => "InventoryItemTrait",
                "window_method_type" => "common",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2021-01-11 00:00:00",
            ),
            array(
                "window_method_code" => "INV00018",
                "window_method_window_code" => "INV00014",
                "window_method_module_id" => 3,
                "window_method_name" => "show-product-details",
                "window_method_request" => "post",
                "window_method_blade" => "manage.inventory.maintenance.includes.productdetails",
                "window_method_action" => "inventory_show_product_details",
                "window_method_traits" => "InventoryItemTrait",
                "window_method_type" => "common",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2021-01-11 00:00:00",
            ),
            array(
                "window_method_code" => "INV00019",
                "window_method_window_code" => "INV00014",
                "window_method_module_id" => 3,
                "window_method_name" => "create-product-page",
                "window_method_request" => "get",
                "window_method_blade" => "manage.inventory.maintenance.InventoryCreateProduct",
                "window_method_action" => "inventory_create_item_page",
                "window_method_traits" => "InventoryItemTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-08-24 00:00:00",
            ),
            array(
                "window_method_code" => "INV00020",
                "window_method_window_code" => "INV00014",
                "window_method_module_id" => 3,
                "window_method_name" => "create-product",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_create_item",
                "window_method_traits" => "InventoryItemTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-01-24 00:00:00",
            ),
            array(
                "window_method_code" => "INV00021",
                "window_method_window_code" => "INV00013",
                "window_method_module_id" => 3,
                "window_method_name" => "create-product-group",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_create_item_group",
                "window_method_traits" => "InventoryItemGroupTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-08-20 00:00:00",
            ),
            array(
                "window_method_code" => "INV00022",
                "window_method_window_code" => "INV00013",
                "window_method_module_id" => 3,
                "window_method_name" => "search-product-group",
                "window_method_request" => "get",
                "window_method_blade" => "manage.inventory.maintenance.includes.productgrouplist",
                "window_method_action" => "inventory_search_item_group",
                "window_method_traits" => "InventoryItemGroupTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-08-20 00:00:00",
            ),
            array(
                "window_method_code" => "INV00023",
                "window_method_window_code" => "INV00013",
                "window_method_module_id" => 3,
                "window_method_name" => "update-item-group",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_update_item_group",
                "window_method_traits" => "InventoryItemGroupTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => NULL,
                "created_by" => 1,
                "created_date" => "2020-08-19 00:00:00",
            ),
            array(
                "window_method_code" => "INV00024",
                "window_method_window_code" => "INV00001",
                "window_method_module_id" => 3,
                "window_method_name" => "delete-department",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_delete_department",
                "window_method_traits" => "InventoryDepartmentTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 3,
                "created_by" => 1,
                "created_date" => "2021-03-15 00:00:00",
            ),
            array(
                "window_method_code" => "INV00025",
                "window_method_window_code" => "INV00001",
                "window_method_module_id" => 3,
                "window_method_name" => "create-department",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_create_department",
                "window_method_traits" => "InventoryDepartmentTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 1,
                "created_by" => 1,
                "created_date" => "2020-08-24 00:00:00",
            ),
            array(
                "window_method_code" => "INV00026",
                "window_method_window_code" => "INV00001",
                "window_method_module_id" => 3,
                "window_method_name" => "update-department",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_update_department",
                "window_method_traits" => "InventoryDepartmentTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 2,
                "created_by" => 1,
                "created_date" => "2021-03-15 00:00:00",
            ),
            array(
                "window_method_code" => "INV00027",
                "window_method_window_code" => "INV00002",
                "window_method_module_id" => 3,
                "window_method_name" => "update-warehouse",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_update_warehouse",
                "window_method_traits" => "InventoryWarehouseTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 2,
                "created_by" => 1,
                "created_date" => "2021-03-16 11:56:31",
            ),
            array(
                "window_method_code" => "INV00028",
                "window_method_window_code" => "INV00002",
                "window_method_module_id" => 3,
                "window_method_name" => "delete-warehouse",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_delete_warehouse",
                "window_method_traits" => "InventoryWarehouseTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 3,
                "created_by" => 1,
                "created_date" => "2021-03-16 11:57:18",
            ),
            array(
                "window_method_code" => "INV00029",
                "window_method_window_code" => "INV00002",
                "window_method_module_id" => 3,
                "window_method_name" => "create-warehouse",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_create_warehouse",
                "window_method_traits" => "InventoryWarehouseTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 1,
                "created_by" => 1,
                "created_date" => "2020-08-24 00:00:00",
            ),
            array(
                "window_method_code" => "INV00030",
                "window_method_window_code" => "INV00003",
                "window_method_module_id" => 3,
                "window_method_name" => "create-unit-measure",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_create_unit_measure",
                "window_method_traits" => "InventoryUnitMeasureTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 1,
                "created_by" => 1,
                "created_date" => "2020-08-24 00:00:00",
            ),
            array(
                "window_method_code" => "INV00031",
                "window_method_window_code" => "INV00003",
                "window_method_module_id" => 3,
                "window_method_name" => "update-unit-measure",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_update_unit_measure",
                "window_method_traits" => "InventoryUnitMeasureTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 2,
                "created_by" => 1,
                "created_date" => "2021-03-16 14:44:55",
            ),
            array(
                "window_method_code" => "INV00032",
                "window_method_window_code" => "INV00003",
                "window_method_module_id" => 3,
                "window_method_name" => "delete-unit-measure",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_delete_unit_measure",
                "window_method_traits" => "InventoryUnitMeasureTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 3,
                "created_by" => 1,
                "created_date" => "2021-03-16 14:45:36",
            ),
            array(
                "window_method_code" => "INV00033",
                "window_method_window_code" => "INV00005",
                "window_method_module_id" => 3,
                "window_method_name" => "update-address",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_update_address",
                "window_method_traits" => "InventoryAddressTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 3,
                "created_by" => 1,
                "created_date" => "2021-03-17 13:52:32",
            ),
            array(
                "window_method_code" => "INV00034",
                "window_method_window_code" => "INV00005",
                "window_method_module_id" => 3,
                "window_method_name" => "retrieve-address",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_retrieve_address",
                "window_method_traits" => "InventoryAddressTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 2,
                "created_by" => 1,
                "created_date" => "2021-03-17 13:42:30",
            ),
            array(
                "window_method_code" => "INV00035",
                "window_method_window_code" => "INV00005",
                "window_method_module_id" => 3,
                "window_method_name" => "create-address",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_create_address",
                "window_method_traits" => "InventoryAddressTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 1,
                "created_by" => 1,
                "created_date" => "2020-08-25 00:00:00",
            ),
            array(
                "window_method_code" => "INV00036",
                "window_method_window_code" => "INV00005",
                "window_method_module_id" => 3,
                "window_method_name" => "delete-address",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_delete_address",
                "window_method_traits" => "InventoryAddressTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 4,
                "created_by" => 1,
                "created_date" => "2021-03-17 14:25:48",
            ),
            array(
                "window_method_code" => "INV00037",
                "window_method_window_code" => "INV00006",
                "window_method_module_id" => 3,
                "window_method_name" => "retrieve-contact",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_retrieve_contact",
                "window_method_traits" => "InventoryContactTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 2,
                "created_by" => 1,
                "created_date" => "2021-03-17 14:40:00",
            ),
            array(
                "window_method_code" => "INV00038",
                "window_method_window_code" => "INV00006",
                "window_method_module_id" => 3,
                "window_method_name" => "update-contact",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_update_contact",
                "window_method_traits" => "InventoryContactTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 3,
                "created_by" => 1,
                "created_date" => "2021-03-17 14:40:26",
            ),
            array(
                "window_method_code" => "INV00039",
                "window_method_window_code" => "INV00006",
                "window_method_module_id" => 3,
                "window_method_name" => "delete-contact",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_delete_contact",
                "window_method_traits" => "InventoryContactTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 4,
                "created_by" => 1,
                "created_date" => "2021-03-17 14:40:51",
            ),
            array(
                "window_method_code" => "INV00040",
                "window_method_window_code" => "INV00006",
                "window_method_module_id" => 3,
                "window_method_name" => "create-contact",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_create_contact",
                "window_method_traits" => "InventoryContactTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 1,
                "created_by" => 1,
                "created_date" => "2020-08-25 00:00:00",
            ),
            array(
                "window_method_code" => "INV00041",
                "window_method_window_code" => "INV00007",
                "window_method_module_id" => 3,
                "window_method_name" => "delete-supplier",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_delete_supplier",
                "window_method_traits" => "InventorySupplierTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 4,
                "created_by" => 1,
                "created_date" => "2021-03-17 16:52:08",
            ),
            array(
                "window_method_code" => "INV00042",
                "window_method_window_code" => "INV00007",
                "window_method_module_id" => 3,
                "window_method_name" => "retrieve-supplier",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_retrieve_supplier",
                "window_method_traits" => "InventorySupplierTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 3,
                "created_by" => 1,
                "created_date" => "2021-03-17 16:52:08",
            ),
            array(
                "window_method_code" => "INV00043",
                "window_method_window_code" => "INV00007",
                "window_method_module_id" => 3,
                "window_method_name" => "update-supplier",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_update_supplier",
                "window_method_traits" => "InventorySupplierTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 2,
                "created_by" => 1,
                "created_date" => "2021-03-17 16:51:35",
            ),
            array(
                "window_method_code" => "INV00044",
                "window_method_window_code" => "INV00007",
                "window_method_module_id" => 3,
                "window_method_name" => "create-supplier",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_create_supplier",
                "window_method_traits" => "InventorySupplierTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 1,
                "created_by" => 1,
                "created_date" => "2020-08-26 00:00:00",
            ),
            array(
                "window_method_code" => "INV00045",
                "window_method_window_code" => "INV00010",
                "window_method_module_id" => 3,
                "window_method_name" => "inventory-delete-customer-basket",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_delete_customer_basket",
                "window_method_traits" => "InventoryBasketTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 5,
                "created_by" => 1,
                "created_date" => "2021-03-30 23:08:29",
            ),
            array(
                "window_method_code" => "INV00046",
                "window_method_window_code" => "INV00010",
                "window_method_module_id" => 3,
                "window_method_name" => "inventory-update-customer-basket-quantity",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_update_customer_basket_quantity",
                "window_method_traits" => "InventoryBasketTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 5,
                "created_by" => 1,
                "created_date" => "2021-03-30 23:08:29",
            ),
            array(
                "window_method_code" => "INV00047",
                "window_method_window_code" => "INV00010",
                "window_method_module_id" => 3,
                "window_method_name" => "inventory-retrieve-customer-basket",
                "window_method_request" => "get",
                "window_method_blade" => "manage.inventory.activity.blades.basketlisting",
                "window_method_action" => "inventory_retrieve_customer_basket",
                "window_method_traits" => "InventoryBasketTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 5,
                "created_by" => 1,
                "created_date" => "2021-03-30 23:08:29",
            ),
            array(
                "window_method_code" => "INV00048",
                "window_method_window_code" => "INV00010",
                "window_method_module_id" => 3,
                "window_method_name" => "inventory-create-customer-basket",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_create_customer_basket",
                "window_method_traits" => "InventoryBasketTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 5,
                "created_by" => 1,
                "created_date" => "2021-03-30 23:08:29",
            ),
            array(
                "window_method_code" => "INV00049",
                "window_method_window_code" => "INV00010",
                "window_method_module_id" => 3,
                "window_method_name" => "inventory-retrieve-customer-order-receipt",
                "window_method_request" => "get",
                "window_method_blade" => "manage.inventory.report.InventoryOrderReceipt",
                "window_method_action" => "inventory_cashier_print_receipt",
                "window_method_traits" => "InventoryCashierReportTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 4,
                "created_by" => 1,
                "created_date" => "2021-03-30 22:24:40",
            ),
            array(
                "window_method_code" => "INV00050",
                "window_method_window_code" => "INV00010",
                "window_method_module_id" => 3,
                "window_method_name" => "cashier-retrieve-product-json",
                "window_method_request" => "get",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_order_retrieve_product_json",
                "window_method_traits" => "InventoryCashierTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 2,
                "created_by" => 1,
                "created_date" => "2021-03-22 14:11:16",
            ),
            array(
                "window_method_code" => "INV00051",
                "window_method_window_code" => "INV00010",
                "window_method_module_id" => 3,
                "window_method_name" => "inventory-retrieve-customer-cashier-modal",
                "window_method_request" => "get",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_retrieve_customer_modal_table",
                "window_method_traits" => "InventoryDataTableTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 4,
                "created_by" => 1,
                "created_date" => "2021-03-30 22:24:40",
            ),
            array(
                "window_method_code" => "INV00052",
                "window_method_window_code" => "INV00010",
                "window_method_module_id" => 3,
                "window_method_name" => "order-retrieve-products",
                "window_method_request" => "get",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_retrieve_product_modal_table",
                "window_method_traits" => "InventoryDataTableTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 3,
                "created_by" => 1,
                "created_date" => "2021-03-22 14:11:16",
            ),
            array(
                "window_method_code" => "INV00053",
                "window_method_window_code" => "INV00010",
                "window_method_module_id" => 3,
                "window_method_name" => "inventory-retrieve-order-history",
                "window_method_request" => "get",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_retrieve_order_receipt_history_modal_table",
                "window_method_traits" => "InventoryDataTableTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 5,
                "created_by" => 1,
                "created_date" => "2021-03-30 23:08:29",
            ),
            array(
                "window_method_code" => "INV00054",
                "window_method_window_code" => "INV00010",
                "window_method_module_id" => 3,
                "window_method_name" => "cashier-retrieve-products",
                "window_method_request" => "get",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_retrieve_product_modal_table",
                "window_method_traits" => "InventoryDataTableTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 1,
                "created_by" => 1,
                "created_date" => "2021-03-22 14:11:16",
            ),
            array(
                "window_method_code" => "INV00055",
                "window_method_window_code" => "INV00010",
                "window_method_module_id" => 3,
                "window_method_name" => "retrieve-customer-order-receipt",
                "window_method_request" => "get",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_order_retrieve_receipt_history",
                "window_method_traits" => "InventoryOrderTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 2,
                "created_by" => 1,
                "created_date" => "2021-03-24 22:58:18",
            ),
            array(
                "window_method_code" => "INV00056",
                "window_method_window_code" => "INV00010",
                "window_method_module_id" => 3,
                "window_method_name" => "retrieve-order-history",
                "window_method_request" => "get",
                "window_method_blade" => "manage.inventory.activity.blades.orderHistory",
                "window_method_action" => "inventory_order_retrieve_history",
                "window_method_traits" => "InventoryOrderTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 6,
                "created_by" => 1,
                "created_date" => "2021-03-30 23:08:29",
            ),
            array(
                "window_method_code" => "INV00057",
                "window_method_window_code" => "INV00010",
                "window_method_module_id" => 3,
                "window_method_name" => "retrieve-customer-order-basket",
                "window_method_request" => "get",
                "window_method_blade" => "manage.inventory.activity.blades.basketlisting",
                "window_method_action" => "inventory_order_retrieve_basket",
                "window_method_traits" => "InventoryOrderTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 5,
                "created_by" => 1,
                "created_date" => "2021-03-30 23:08:29",
            ),
            array(
                "window_method_code" => "INV00058",
                "window_method_window_code" => "INV00010",
                "window_method_module_id" => 3,
                "window_method_name" => "create-customer-order-basket",
                "window_method_request" => "post",
                "window_method_blade" => "manage.inventory.activity.blades.basketlisting",
                "window_method_action" => "inventory_order_create_basket",
                "window_method_traits" => "InventoryOrderTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 3,
                "created_by" => 1,
                "created_date" => "2021-03-24 22:58:18",
            ),
            array(
                "window_method_code" => "INV00059",
                "window_method_window_code" => "INV00010",
                "window_method_module_id" => 3,
                "window_method_name" => "create-customer-order-receipt",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_order_create_receipt",
                "window_method_traits" => "InventoryOrderTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 2,
                "created_by" => 1,
                "created_date" => "2021-03-24 22:58:18",
            ),
            array(
                "window_method_code" => "INV00060",
                "window_method_window_code" => "INV00011",
                "window_method_module_id" => 3,
                "window_method_name" => "delete-customer",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_delete_customer",
                "window_method_traits" => "InventoryCustomerTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 3,
                "created_by" => 1,
                "created_date" => "2021-03-17 20:21:36",
            ),
            array(
                "window_method_code" => "INV00061",
                "window_method_window_code" => "INV00011",
                "window_method_module_id" => 3,
                "window_method_name" => "create-customer",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_create_customer",
                "window_method_traits" => "InventoryCustomerTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 1,
                "created_by" => 1,
                "created_date" => "2020-08-26 00:00:00",
            ),
            array(
                "window_method_code" => "INV00062",
                "window_method_window_code" => "INV00011",
                "window_method_module_id" => 3,
                "window_method_name" => "retrieve-customer",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_retrieve_customer",
                "window_method_traits" => "InventoryCustomerTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 2,
                "created_by" => 1,
                "created_date" => "2021-03-17 20:20:53",
            ),
            array(
                "window_method_code" => "INV00063",
                "window_method_window_code" => "INV00011",
                "window_method_module_id" => 3,
                "window_method_name" => "update-customer",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_update_customer",
                "window_method_traits" => "InventoryCustomerTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 3,
                "created_by" => 1,
                "created_date" => "2021-03-17 20:21:36",
            ),
            array(
                "window_method_code" => "INV00064",
                "window_method_window_code" => "INV00011",
                "window_method_module_id" => 3,
                "window_method_name" => "inventory-retrieve-customers-datatable",
                "window_method_request" => "get",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_retrieve_customers_data",
                "window_method_traits" => "InventoryDataTableTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 5,
                "created_by" => 1,
                "created_date" => "2021-03-30 23:08:29",
            ),
            array(
                "window_method_code" => "INV00065",
                "window_method_window_code" => "INV00012",
                "window_method_module_id" => 3,
                "window_method_name" => "inventory-update-customer-basket-quantity",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_update_customer_basket_quantity",
                "window_method_traits" => "InventoryBasketTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 5,
                "created_by" => 1,
                "created_date" => "2021-03-30 23:08:29",
            ),
            array(
                "window_method_code" => "INV00066",
                "window_method_window_code" => "INV00012",
                "window_method_module_id" => 3,
                "window_method_name" => "inventory-retrieve-customer-basket",
                "window_method_request" => "get",
                "window_method_blade" => "manage.inventory.activity.blades.basketlisting",
                "window_method_action" => "inventory_retrieve_customer_basket",
                "window_method_traits" => "InventoryBasketTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 3,
                "created_by" => 1,
                "created_date" => "2021-03-24 22:58:18",
            ),
            array(
                "window_method_code" => "INV00067",
                "window_method_window_code" => "INV00012",
                "window_method_module_id" => 3,
                "window_method_name" => "inventory-delete-customer-basket",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_delete_customer_basket",
                "window_method_traits" => "InventoryBasketTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 5,
                "created_by" => 1,
                "created_date" => "2021-03-30 23:08:29",
            ),
            array(
                "window_method_code" => "INV00068",
                "window_method_window_code" => "INV00012",
                "window_method_module_id" => 3,
                "window_method_name" => "inventory-create-customer-basket",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_create_customer_basket",
                "window_method_traits" => "InventoryBasketTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 5,
                "created_by" => 1,
                "created_date" => "2021-03-30 23:08:29",
            ),
            array(
                "window_method_code" => "INV00069",
                "window_method_window_code" => "INV00012",
                "window_method_module_id" => 3,
                "window_method_name" => "inventory-retrieve-customer-cashier-receipt",
                "window_method_request" => "get",
                "window_method_blade" => "manage.inventory.report.InventoryCashierReceipt",
                "window_method_action" => "inventory_cashier_print_receipt",
                "window_method_traits" => "InventoryCashierReportTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 4,
                "created_by" => 1,
                "created_date" => "2021-03-30 22:24:40",
            ),
            array(
                "window_method_code" => "INV00070",
                "window_method_window_code" => "INV00012",
                "window_method_module_id" => 3,
                "window_method_name" => "cashier-print-receipt",
                "window_method_request" => "post",
                "window_method_blade" => "manage.inventory.report.InventoryCashierReceipt",
                "window_method_action" => "inventory_cashier_print_receipt",
                "window_method_traits" => "InventoryCashierReportTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 1,
                "created_by" => 1,
                "created_date" => "2021-04-17 20:36:17",
            ),
            array(
                "window_method_code" => "INV00071",
                "window_method_window_code" => "INV00012",
                "window_method_module_id" => 3,
                "window_method_name" => "inventory-print-customer-receipt",
                "window_method_request" => "get",
                "window_method_blade" => "manage.inventory.report.InventoryCashierPrintReceipt",
                "window_method_action" => "inventory_cashier_print_receipt",
                "window_method_traits" => "InventoryCashierReportTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 4,
                "created_by" => 1,
                "created_date" => "2021-03-30 22:24:40",
            ),
            array(
                "window_method_code" => "INV00072",
                "window_method_window_code" => "INV00012",
                "window_method_module_id" => 3,
                "window_method_name" => "cashier-retrieve-product-json",
                "window_method_request" => "get",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_cashier_retrieve_product_json",
                "window_method_traits" => "InventoryCashierTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 2,
                "created_by" => 1,
                "created_date" => "2021-03-22 14:11:16",
            ),
            array(
                "window_method_code" => "INV00073",
                "window_method_window_code" => "INV00012",
                "window_method_module_id" => 3,
                "window_method_name" => "cashier-create-receipt",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_cashier_create_receipt",
                "window_method_traits" => "InventoryCashierTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 2,
                "created_by" => 1,
                "created_date" => "2021-03-24 22:58:18",
            ),
            array(
                "window_method_code" => "INV00074",
                "window_method_window_code" => "INV00012",
                "window_method_module_id" => 3,
                "window_method_name" => "cashier-create-customer",
                "window_method_request" => "post",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_create_customer",
                "window_method_traits" => "InventoryCustomerTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 4,
                "created_by" => 1,
                "created_date" => "2021-03-30 22:24:40",
            ),
            array(
                "window_method_code" => "INV00075",
                "window_method_window_code" => "INV00012",
                "window_method_module_id" => 3,
                "window_method_name" => "inventory-retrieve-customer-cashier-modal",
                "window_method_request" => "get",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_retrieve_customer_modal_table",
                "window_method_traits" => "InventoryDataTableTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 4,
                "created_by" => 1,
                "created_date" => "2021-03-30 22:24:40",
            ),
            array(
                "window_method_code" => "INV00076",
                "window_method_window_code" => "INV00012",
                "window_method_module_id" => 3,
                "window_method_name" => "inventory-retrieve-cashier-history",
                "window_method_request" => "get",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_retrieve_cashier_receipt_history_modal_table",
                "window_method_traits" => "InventoryDataTableTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 5,
                "created_by" => 1,
                "created_date" => "2021-03-30 23:08:29",
            ),
            array(
                "window_method_code" => "INV00077",
                "window_method_window_code" => "INV00012",
                "window_method_module_id" => 3,
                "window_method_name" => "cashier-retrieve-products",
                "window_method_request" => "get",
                "window_method_blade" => NULL,
                "window_method_action" => "inventory_retrieve_product_modal_table",
                "window_method_traits" => "InventoryDataTableTrait",
                "window_method_type" => "secure",
                "status" => 1,
                "order_level" => 1,
                "created_by" => 1,
                "created_date" => "2021-03-22 14:11:16",
            ),
        );
    }
}