<?php

use Illuminate\Database\Seeder;

class UsersAccessWindowMethodSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    protected function databaseConnection()
    {
        return DB::connection('mysql');
    }

    public function run()
    {
        $this->databaseConnection()->table('users_access_window_method')->insert(
            array(
                array(
                    "access_users_id" => 1,
                    "access_module_id" => 2,
                    "access_company_id" => 1,
                    "access_window_method_code" => 'ACC00001',
                    "status" => 1,
                    "order_level" => 1,
                    "created_by" => 1,
                    "created_date" => now(),
                ),
                array(
                    "access_users_id" => 1,
                    "access_module_id" => 2,
                    "access_company_id" => 1,
                    "access_window_method_code" => 'ACC00002',
                    "status" => 1,
                    "order_level" => 1,
                    "created_by" => 1,
                    "created_date" => now(),
                ),
                array(
                    "access_users_id" => 1,
                    "access_module_id" => 2,
                    "access_company_id" => 1,
                    "access_window_method_code" => 'ACC00003',
                    "status" => 1,
                    "order_level" => 1,
                    "created_by" => 1,
                    "created_date" => now(),
                ),
                array(
                    "access_users_id" => 1,
                    "access_module_id" => 2,
                    "access_company_id" => 1,
                    "access_window_method_code" => 'ACC00004',
                    "status" => 1,
                    "order_level" => 1,
                    "created_by" => 1,
                    "created_date" => now(),
                ),
                array(
                    "access_users_id" => 1,
                    "access_module_id" => 2,
                    "access_company_id" => 1,
                    "access_window_method_code" => 'ACC00005',
                    "status" => 1,
                    "order_level" => 1,
                    "created_by" => 1,
                    "created_date" => now(),
                ),
                array(
                    "access_users_id" => 1,
                    "access_module_id" => 2,
                    "access_company_id" => 1,
                    "access_window_method_code" => 'ACC00006',
                    "status" => 1,
                    "order_level" => 1,
                    "created_by" => 1,
                    "created_date" => now(),
                ),
                array(
                    "access_users_id" => 1,
                    "access_module_id" => 2,
                    "access_company_id" => 1,
                    "access_window_method_code" => 'ACC00007',
                    "status" => 1,
                    "order_level" => 1,
                    "created_by" => 1,
                    "created_date" => now(),
                ),
                array(
                    "access_users_id" => 1,
                    "access_module_id" => 2,
                    "access_company_id" => 1,
                    "access_window_method_code" => 'ACC00008',
                    "status" => 1,
                    "order_level" => 1,
                    "created_by" => 1,
                    "created_date" => now(),
                ),
                array(
                    "access_users_id" => 1,
                    "access_module_id" => 2,
                    "access_company_id" => 1,
                    "access_window_method_code" => 'ACC00009',
                    "status" => 1,
                    "order_level" => 1,
                    "created_by" => 1,
                    "created_date" => now(),
                ),
                array(
                    "access_users_id" => 1,
                    "access_module_id" => 2,
                    "access_company_id" => 1,
                    "access_window_method_code" => 'ACC00010',
                    "status" => 1,
                    "order_level" => 1,
                    "created_by" => 1,
                    "created_date" => now(),
                ),
                array(
                    "access_users_id" => 1,
                    "access_module_id" => 2,
                    "access_company_id" => 1,
                    "access_window_method_code" => 'ACC00011',
                    "status" => 1,
                    "order_level" => 1,
                    "created_by" => 1,
                    "created_date" => now(),
                ),
                array(
                    "access_users_id" => 1,
                    "access_module_id" => 2,
                    "access_company_id" => 1,
                    "access_window_method_code" => 'ACC00012',
                    "status" => 1,
                    "order_level" => 1,
                    "created_by" => 1,
                    "created_date" => now(),
                ),
                array(
                    "access_users_id" => 1,
                    "access_module_id" => 2,
                    "access_company_id" => 1,
                    "access_window_method_code" => 'ACC00013',
                    "status" => 1,
                    "order_level" => 1,
                    "created_by" => 1,
                    "created_date" => now(),
                ),
                array(
                    "access_users_id" => 1,
                    "access_module_id" => 2,
                    "access_company_id" => 1,
                    "access_window_method_code" => 'ACC00014',
                    "status" => 1,
                    "order_level" => 1,
                    "created_by" => 1,
                    "created_date" => now(),
                ),
                array(
                    "access_users_id" => 1,
                    "access_module_id" => 2,
                    "access_company_id" => 1,
                    "access_window_method_code" => 'ACC00015',
                    "status" => 1,
                    "order_level" => 1,
                    "created_by" => 1,
                    "created_date" => now(),
                ),
                array(
                    "access_users_id" => 1,
                    "access_module_id" => 2,
                    "access_company_id" => 1,
                    "access_window_method_code" => 'ACC00016',
                    "status" => 1,
                    "order_level" => 1,
                    "created_by" => 1,
                    "created_date" => now(),
                ),
                array(
                    "access_users_id" => 1,
                    "access_module_id" => 2,
                    "access_company_id" => 1,
                    "access_window_method_code" => 'ACC00017',
                    "status" => 1,
                    "order_level" => 1,
                    "created_by" => 1,
                    "created_date" => now(),
                ),
                array(
                    "access_users_id" => 1,
                    "access_module_id" => 2,
                    "access_company_id" => 1,
                    "access_window_method_code" => 'ACC00018',
                    "status" => 1,
                    "order_level" => 1,
                    "created_by" => 1,
                    "created_date" => now(),
                ),
                array(
                    "access_users_id" => 1,
                    "access_module_id" => 2,
                    "access_company_id" => 1,
                    "access_window_method_code" => 'ACC00019',
                    "status" => 1,
                    "order_level" => 1,
                    "created_by" => 1,
                    "created_date" => now(),
                ),
                array(
                    "access_users_id" => 1,
                    "access_module_id" => 2,
                    "access_company_id" => 1,
                    "access_window_method_code" => 'ACC00020',
                    "status" => 1,
                    "order_level" => 1,
                    "created_by" => 1,
                    "created_date" => now(),
                ),
                array(
                    "access_users_id" => 1,
                    "access_module_id" => 2,
                    "access_company_id" => 1,
                    "access_window_method_code" => 'ACC00021',
                    "status" => 1,
                    "order_level" => 1,
                    "created_by" => 1,
                    "created_date" => now(),
                ),
                array(
                    "access_users_id" => 1,
                    "access_module_id" => 2,
                    "access_company_id" => 1,
                    "access_window_method_code" => 'ACC00022',
                    "status" => 1,
                    "order_level" => 1,
                    "created_by" => 1,
                    "created_date" => now(),
                ),
                array(
                    "access_users_id" => 1,
                    "access_module_id" => 2,
                    "access_company_id" => 1,
                    "access_window_method_code" => 'ACC00023',
                    "status" => 1,
                    "order_level" => 1,
                    "created_by" => 1,
                    "created_date" => now(),
                ),
                array(
                    "access_users_id" => 1,
                    "access_module_id" => 2,
                    "access_company_id" => 1,
                    "access_window_method_code" => 'ACC00024',
                    "status" => 1,
                    "order_level" => 1,
                    "created_by" => 1,
                    "created_date" => now(),
                ),
                array(
                    "access_users_id" => 1,
                    "access_module_id" => 2,
                    "access_company_id" => 1,
                    "access_window_method_code" => 'ACC00025',
                    "status" => 1,
                    "order_level" => 1,
                    "created_by" => 1,
                    "created_date" => now(),
                ),
                array(
                    "access_users_id" => 1,
                    "access_module_id" => 2,
                    "access_company_id" => 1,
                    "access_window_method_code" => 'ACC00026',
                    "status" => 1,
                    "order_level" => 1,
                    "created_by" => 1,
                    "created_date" => now(),
                ),
                array(
                    "access_users_id" => 1,
                    "access_module_id" => 2,
                    "access_company_id" => 1,
                    "access_window_method_code" => 'ACC00027',
                    "status" => 1,
                    "order_level" => 1,
                    "created_by" => 1,
                    "created_date" => now(),
                ),
                array(
                    "access_users_id" => 1,
                    "access_module_id" => 2,
                    "access_company_id" => 1,
                    "access_window_method_code" => 'ACC00028',
                    "status" => 1,
                    "order_level" => 1,
                    "created_by" => 1,
                    "created_date" => now(),
                ),
            )
        );
    }
}
